In [1]:
import numpy as np
#1-D array
a=np.array([5,6,9])


In [2]:
a[0]


5

In [4]:
a[1]
a.ndim#to pringt

1

In [5]:
a=np.array([[1,2],[5,6],[6,7]])
a.ndim#it will show the dimension as 2 

2

In [7]:
#it will show the item size of array that stored here it is int thats why it give 4 byte
a.itemsize

4

In [8]:
a.dtype

dtype('int32')

In [9]:
a=np.array([[12,14],[13,15],[16,17]],dtype=np.float64)


In [10]:
a.itemsize

8

In [13]:
a.size#it will print total no of element

6

In [14]:
a.shape

(3, 2)

In [17]:
a=np.array([[12,14],[13,15],[16,17]],dtype=complex)
a

array([[12.+0.j, 14.+0.j],
       [13.+0.j, 15.+0.j],
       [16.+0.j, 17.+0.j]])

In [19]:
#you want to array with o's
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.arange(1,5)

array([1, 2, 3, 4])

In [23]:
np.arange(1,5,2)#it will print element like 1,3 means 1+2(Gap)=3 like this

array([1, 3])

In [24]:
np.linspace(1,5,10)#it will generate 10 number that is linearly space


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [29]:
#rehsape
a=np.array([[1,2,3,4],[3,4,5,4],[5,6,7,4]])
a

array([[1, 2, 3, 4],
       [3, 4, 5, 4],
       [5, 6, 7, 4]])

In [30]:
a.shape

(3, 4)

In [31]:
a.reshape(4,3)#dimeension should compatible should original dimension

array([[1, 2, 3],
       [4, 3, 4],
       [5, 4, 5],
       [6, 7, 4]])

In [32]:
#ravel -flatten the  array makes one dimensional
a.ravel()

array([1, 2, 3, 4, 3, 4, 5, 4, 5, 6, 7, 4])

In [33]:
#mathemetical function
a.max()
#print maximum element of array

7

In [34]:
a.min()

1

In [35]:
a.sum()#it will sum all the element

48

In [36]:
a.mean()

4.0

1. axis=0 will be columns
1. axis=1 will be rows

In [38]:
a.sum(axis=0)#it will add column wise

array([ 9, 12, 15, 12])

In [39]:
a.sum(axis=1)

array([10, 16, 22])

In [41]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.        , 2.23606798, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.        ]])

In [42]:
np.std(a)

1.5811388300841898

In [43]:
#summation operation
a=np.array([[5,6],[7,8]])
b=np.array([[8,9],[10,11]])
a+b

array([[13, 15],
       [17, 19]])

In [44]:
a-b

array([[-3, -3],
       [-3, -3]])

In [45]:
a*b

array([[40, 54],
       [70, 88]])

In [46]:
a/b

array([[0.625     , 0.66666667],
       [0.7       , 0.72727273]])

In [47]:
a.dot(b)#matric product

array([[100, 111],
       [136, 151]])