## Topics
1. Indexing and slicing
2. Iterating through arrays
3. Stacking together two arrays
4. Indexing with boolean arrays

In [1]:
import numpy as np


In [2]:
a=np.array([6,7,8])
a[0:2]

array([6, 7])

In [3]:
a[-1]

8

In [4]:
#lets go to multidimensional array
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [5]:
a[1,2]

3

In [6]:
a[0:2,2]
#it will go to oth row print 2 element that is 8 and then it will go to 2nd element in 1 st row.

array([8, 3])

In [7]:
a[-1]#it will print last row

array([9, 3, 2])

In [8]:
a[-1,0:2]#it will print last row's 0 th and 1st element

array([9, 3])

In [11]:
a[:,1:3]#here : means it will go to all the rows and it wil print 1st element and 2nd element of each row 

array([[7, 8],
       [2, 3],
       [3, 2]])

In [12]:
#if i want iterate through rows
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [13]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [14]:
for cell in a.flat:
    print(cell)
    #it will flatten the array

6
7
8
1
2
3
9
3
2


In [16]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
np.vstack((a,b))#vertical stacking 

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
np.hstack((a,b))#horizontal stack

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [22]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
#horizontal split
result=np.hsplit(a,3)#it will split the array into 03 different array

In [24]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [25]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [26]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [28]:
#vertical split
result=np.vsplit(a,2)

In [29]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [30]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

### Indexing with boolean array

In [31]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
a[b]
#it look at the array whenewer you found true it written the value

array([ 5,  6,  7,  8,  9, 10, 11])

In [37]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])